[package]
name = "rust-starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random-string = "0.1.0"
random-number = "0.1.7"
rand = "0.8"
rayon = "1.5"